FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG VERSION
ARG ISTIO_VERSION

LABEL com.redhat.component="maistra-cni"
LABEL name="maistra/istio-cni-ubi8"
LABEL version="${VERSION}"
LABEL istio_version="${ISTIO_VERSION}"
LABEL summary="Red Hat Istio-CNI plugin installer OpenShift container image"
LABEL description="Red Hat Istio-CNI plugin installer OpenShift container image"
LABEL io.k8s.display-name="Red Hat Istio-CNI plugin installer"
LABEL io.openshift.tags="istio"
LABEL io.openshift.expose-services=""
LABEL maintainer="Istio Feedback <istio-feedback@redhat.com>"
ENV container="oci"
ENV ISTIO_VERSION="${ISTIO_VERSION}"

RUN microdnf update -y && \
    microdnf clean all

COPY istio-cni /opt/cni/bin/istio-cni
COPY install-cni /usr/local/bin/install-cni
COPY istio-cni-taint /opt/local/bin/istio-cni-taint

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/usr/local/bin/install-cni"]
